name: release

on:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test --blame-hang-timeout 2m $(find *.sln -print -quit)

  release:
    runs-on: ubuntu-latest
    container: alpine:3.15
    needs: [test]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install deps
        run: apk update && apk add --no-cache docker-cli openrc git
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_REGISTRY_USER}} -p ${{secrets.DOCKER_HUB_REGISTRY_PASSWORD}}
      - name: Build image
        run: docker build --pull -f ./src/Dockerfile -t jonasmh/husqvarna2mqtt:${{ github.event.release.tag_name }} -t jonasmh/husqvarna2mqtt:latest .
      - name: Push imagewith 
        run: |-
          docker push jonasmh/husqvarna2mqtt:${{ github.event.release.tag_name }};
          docker push jonasmh/husqvarna2mqtt:latest;
